Repository WANTED-TEAM03/pre-onboarding-10th-1-3, pull requests merged in 2023-04, with the labels that each got.

#10 Feat/#6 Assignment 3 기능 구현
  .eslintcache
  .eslintrc.json
  .gitignore
  src/App.tsx
  src/constants/config.ts
  src/hooks/useCheckAuth.ts
  src/index.tsx
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Todo/index.tsx
  src/pages/Welcome/index.tsx
  src/routes/Routes.tsx
  src/routes/_globalLayout.tsx
  src/services/apiClient.tsx
  src/services/auth.ts
  src/styles/media.scss
  src/styles/reset.scss
  src/types/authForm.ts
Labels: FEAT, REFACTOR

#5 Feat/#2 Assignment 1 기능 구현
  src/components/AuthForm/index.tsx
  src/components/AuthForm/styles.module.scss
  src/constants/auth.ts
  src/hooks/useInput.ts
  src/pages/SignIn/index.tsx
  src/pages/SignUp/index.tsx
  src/pages/Todo/index.tsx
  src/services/auth.ts
  src/types/authForm.ts
  src/utils/authValidator.ts
Labels: FEAT, FIX

#7 Feat/#1 Assignment 2 기능 구현
  src/components/AuthForm/index.tsx
  src/constants/auth.ts
  src/pages/Signin/index.tsx
  src/pages/Signin/styles.module.scss
  src/pages/Signup/index.tsx
  src/pages/Signup/styles.module.scss
  src/services/auth.ts
  src/utils/onKeydown.ts
Labels: FEAT

#17 Todo 페이지 마크업
  src/components/AddTodoInput/index.tsx
  src/components/AddTodoInput/styles.module.scss
  src/components/TodoItem/index.tsx
  src/components/TodoItem/styles.module.scss
  src/pages/Signin/index.tsx
  src/pages/Signin/styles.module.scss
  src/pages/Signup/index.tsx
  src/pages/Signup/styles.module.scss
  src/pages/Todo/index.tsx
  src/pages/Todo/styles.module.scss
  src/types/todo.d.ts
Labels: FEAT

#14 Feat/#13 Welcome페이지 및 Navbar 구현, input에 keydown 적용
  .eslintrc.json
  src/assets/todo_background.png
  src/components/AuthForm/index.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/styles.module.scss
  src/constants/config.ts
  src/pages/Welcome/index.tsx
  src/pages/Welcome/styles.module.scss
  src/routes/_globalLayout.tsx
  src/services/apiClient.ts
  src/services/auth.ts
  src/services/todo.ts
Labels: FEAT, REFACTOR, STYLE

#25 Feat/#22
  .eslintrc.json
  src/assets/todo_background.png
  src/components/AddTodoInput/index.tsx
  src/components/AddTodoInput/styles.module.scss
  src/components/AuthForm/index.tsx
  src/components/Navbar/index.tsx
  src/components/Navbar/styles.module.scss
  src/components/TodoItem/index.tsx
  src/components/TodoItem/styles.module.scss
  src/constants/auth.ts
  src/constants/config.ts
  src/pages/Todo/index.tsx
  src/pages/Todo/styles.module.scss
  src/pages/Welcome/index.tsx
  src/pages/Welcome/styles.module.scss
  src/routes/_globalLayout.tsx
  src/services/apiClient.ts
  src/services/auth.ts
  src/services/todo.ts
  src/types/todo.d.ts
  src/utils/onKeydown.ts
Labels: FEAT

#23 Feat/#19 Assignment 9 기능 구현
  src/components/TodoItem/index.tsx
  src/pages/Todo/index.tsx
  src/services/todo.ts
Labels: FEAT

#26 Assignment 7 기능 merge
  src/components/TodoItem/index.tsx
  src/components/TodoItem/styles.module.scss
Labels: FEAT

#27 Feat/#20 Assignment 10 기능 구현
  src/components/AddTodoInput/index.tsx
  src/components/TodoItem/index.tsx
  src/pages/Todo/index.tsx
Labels: FEAT, REFACTOR

#28 Feat/#24 Todo 기능 구현 및 병합
  src/components/AddTodoInput/index.tsx
  src/components/TodoItem/index.tsx
  src/components/TodoItem/styles.module.scss
  src/pages/Todo/index.tsx
  src/pages/Todo/styles.module.scss
  src/services/apiClient.ts
  src/services/todo.ts
Labels: FEAT, FIX, REFACTOR

#31 Refactor, Fix/#30 Todo 업데이트 기능 수정
  src/components/TodoItem/index.tsx
  src/pages/Todo/index.tsx
Labels: FIX, REFACTOR

#34 [STYLE] : 투두 리스트 스크롤바 숨기기
  src/pages/Todo/styles.module.scss
Labels: STYLE

#36 [DOCS] : README.md 파일 수정
  README.md
Labels: DOCS

#38 Merge develop to main
  .eslintrc.json
  README.md
  public/favicon.ico
  public/index.html
  src/App.tsx
  src/assets/todo_background.png
  src/components/AddTodoInput/index.tsx
  src/components/AddTodoInput/styles.module.scss
  src/components/AuthForm/index.tsx
  src/components/Loading/index.tsx
  src/components/Loading/styles.module.scss
  src/components/Navbar/index.tsx
  src/components/Navbar/styles.module.scss
  src/components/TodoItem/index.tsx
  src/components/TodoItem/styles.module.scss
  src/constants/auth.ts
  src/constants/config.ts
  src/pages/Todo/index.tsx
  src/pages/Todo/styles.module.scss
  src/pages/Welcome/index.tsx
  src/pages/Welcome/styles.module.scss
  src/routes/_globalLayout.tsx
  src/services/apiClient.ts
  src/services/auth.ts
  src/services/todo.ts
  src/types/todo.d.ts
  src/utils/onKeydown.ts
Labels: DOCS
